name: Update Descope Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Update versions in HTML and JavaScript files
        run: |
          chmod +x ./.github/workflows/update-versions.sh
          ./.github/workflows/update-versions.sh

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "Update @descope dependencies to actual latest versions"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update webjs-sdk and web-component versions
          title: "Automated Dependency Update $(date +'%Y-%m-%d %H:%M:%S')"
          body: "This is an automated pull request to update the versions of @descope/webjs-sdk and @descope/web-component."
          branch: "update-dependencies-${{ github.run_id }}"
          base: "main"
